services:
  - type: web
    name: biblia-en-contexto-api
    runtime: node
    plan: free
    rootDir: Biblia-en-Contexto/server
    buildCommand: npm install && npx prisma generate
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: DIRECT_URL
        sync: false
      - key: CLIENT_URL
        sync: false
      - key: AUTH_SECRET
        sync: false

  - type: web
    name: biblia-en-contexto-web
    runtime: static
    rootDir: Biblia-en-Contexto/client
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        sync: false
